import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import axios from 'axios';
import './style.css';
const API='http://localhost:5000/api';
function App(){const [services,setServices]=useState([]);const [bookings,setBookings]=useState([]);const [form,setForm]=useState({customerName:'',carModel:'',serviceId:1,appointmentDate:''});
useEffect(()=>{axios.get(API+'/services').then(r=>setServices(r.data)).catch(()=>setServices([{id:1,name:'Oil Change',description:'Engine oil and filter service',price:50},{id:2,name:'Brake Service',description:'Brake inspection and maintenance',price:100},{id:3,name:'Full Car Wash',description:'Premium exterior and interior wash',price:35}]));},[]);
const book=e=>{e.preventDefault();axios.post(API+'/bookings',form).then(r=>setBookings([...bookings,r.data])).catch(()=>setBookings([...bookings,{...form,id:Date.now(),status:'Pending'}]));};
return <div><header><h1>AutoCare Pro</h1><p>Premium Car Services</p></header><main><section className="hero"><h2>Keep Your Car in Top Shape</h2><p>Professional automotive services you can trust.</p></section><h2>Our Services</h2><div className="grid">{services.map(s=><article key={s.id}><h3>{s.name}</h3><p>{s.description}</p><b>${s.price}</b></article>)}</div><h2>Book a Service</h2><form onSubmit={book}><input placeholder="Your name" required value={form.customerName} onChange={e=>setForm({...form,customerName:e.target.value})}/><input placeholder="Car model" required value={form.carModel} onChange={e=>setForm({...form,carModel:e.target.value})}/><select value={form.serviceId} onChange={e=>setForm({...form,serviceId:+e.target.value})}>{services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input type="datetime-local" required value={form.appointmentDate} onChange={e=>setForm({...form,appointmentDate:e.target.value})}/><button>Book Now</button></form><h2>Bookings</h2>{bookings.map(b=><div className="booking" key={b.id}><b>{b.customerName}</b> — {b.carModel} — {b.status||'Pending'}</div>)}</main></div>};createRoot(document.getElementById('root')).render(<App/>);
